---
apiVersion: v1
kind: Pod
metadata:
  name: fclub-orig-pod
  namespace: jenkins-ns
  labels:
    app: fclub
    type: frontend
spec:
  containers:
    - name: fclub-orig-ctr
      image: gcr.io/bold-bond-303111/fitness-website:version1.0
